name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
    steps:
      - uses: actions/checkout@v2

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add branch name to environment
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Buildah Build
        id: buildah-build
        uses: redhat-actions/buildah-build@v2.12
        with:
          # The name (reference) of the image to build
          dockerfiles: . 
          image: publish-to-gcr
          tags: latest ${{ github.sha }} ${{ env.BRANCH }}
          # The labels of the image to build. Seperate by newline. For example, "io.containers.capabilities=sys_admin,mknod".
          # labels: # optional

      - name: Push To quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah-build.outputs.image }}
          tags: ${{ steps.buildah-build.outputs.tags }}
          registry: ghcr.io/${{ github.actor}}
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
