name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2.12
        with:
          # The name (reference) of the image to build
          image: surreymagpie/publish-to-gcr
          # tags: # optional, default is latest
          # The labels of the image to build. Seperate by newline. For example, "io.containers.capabilities=sys_admin,mknod".
          labels: # optional
          dockerfiles: . 
